In [1]:
import torch
import numpy as np

# Index 기능 사용하기

In [3]:
x = torch.rand(4, 3)
x

tensor([[0.6435, 0.7682, 0.4348],
        [0.7476, 0.0215, 0.8527],
        [0.9873, 0.2223, 0.1460],
        [0.5686, 0.2534, 0.1374]])

In [4]:
torch.index_select(x, 0, torch.LongTensor([0, 2]))

tensor([[0.6435, 0.7682, 0.4348],
        [0.9873, 0.2223, 0.1460]])

In [5]:
x[:, 0]
# 첫번째 열을 슬라이싱

tensor([0.6435, 0.7476, 0.9873, 0.5686])

In [6]:
x[0, :]
# 첫번째 행을 슬라이싱

tensor([0.6435, 0.7682, 0.4348])

In [7]:
x[0:2, 0:2]

tensor([[0.6435, 0.7682],
        [0.7476, 0.0215]])

In [8]:
x = torch.randn(2, 3)
x

tensor([[ 0.4469,  0.5960,  0.4496],
        [ 0.1720, -1.3377, -0.4189]])

In [10]:
mask = torch.ByteTensor([[0, 0, 1], [0, 1, 0]])
torch.masked_select(x, mask)
# bool 형태로 값들을 뽑아냄

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:1356.)
  


tensor([ 0.4496, -1.3377])

# Join(cat, stack) 기능 사용하기

In [11]:
x = torch.cuda.FloatTensor([[1, 2, 3], [4, 5, 6]])
y = torch.cuda.FloatTensor([[-1, -2, -3], [-4, -5, -6]])
z1 = torch.cat([x, y], dim=0)
z1

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]], device='cuda:0')

In [12]:
z2 = torch.cat([x, y], dim=1)
z2
# 즉 dim으로 가로로 합칠지 세로로 합칠지 결정

tensor([[ 1.,  2.,  3., -1., -2., -3.],
        [ 4.,  5.,  6., -4., -5., -6.]], device='cuda:0')

In [16]:
x_stack = torch.stack([x, x, x, x], dim=0)
print(x_stack.size())
x_stack

torch.Size([4, 2, 3])


tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]], device='cuda:0')

In [17]:
x_stack_1 = torch.stack([x, x, x, x], dim = 1)
print(x_stack_1.size())
x_stack_1

torch.Size([2, 4, 3])


tensor([[[1., 2., 3.],
         [1., 2., 3.],
         [1., 2., 3.],
         [1., 2., 3.]],

        [[4., 5., 6.],
         [4., 5., 6.],
         [4., 5., 6.],
         [4., 5., 6.]]], device='cuda:0')

# slicing 기능 사용하기

In [18]:
x_1, x_2 = torch.chunk(z1, 2, dim=0)
y_1, y_2, y_3 = torch.chunk(z1, 3, dim =1)
# tensor를 몇부분으로 나누는 함수

In [19]:
print(x_1)
print(x_2)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')
tensor([[-1., -2., -3.],
        [-4., -5., -6.]], device='cuda:0')


In [20]:
print(y_1)
print(y_2)
print(y_3)

tensor([[ 1.],
        [ 4.],
        [-1.],
        [-4.]], device='cuda:0')
tensor([[ 2.],
        [ 5.],
        [-2.],
        [-5.]], device='cuda:0')
tensor([[ 3.],
        [ 6.],
        [-3.],
        [-6.]], device='cuda:0')


# squeezing 기능 사용하기

In [21]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [22]:
y = torch.squeeze(x)
y.size()
# 치수가 1인 차원이 다 날아감

torch.Size([2, 2, 2])

In [23]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [24]:
y = torch.squeeze(x, 1)
y.size()
# 즉 두번째 매개변수는 지정된 차원만 압축한다.

torch.Size([2, 2, 1, 2])

In [26]:
x = torch.zeros(2, 3, 4)
torch.unsqueeze(x, 0).size()

torch.Size([1, 2, 3, 4])

In [27]:
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, 0)

tensor([[1, 2, 3, 4]])

In [28]:
torch.unsqueeze(x, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [29]:
torch.unsqueeze(x, 1).size()

# 즉 unsqueeze로 차원을 치수가 1인 차원을 추가 가능

torch.Size([4, 1])

# Initialization

In [30]:
import torch.nn.init as init

In [33]:
x1 = init.uniform_(torch.FloatTensor(3, 4), a=0, b=9)
x1
# uniform 분포의 텐서

tensor([[0.4365, 7.6270, 4.0732, 8.2867],
        [4.2590, 6.5414, 7.8734, 8.3282],
        [1.9533, 4.8981, 3.1391, 5.3168]])

In [35]:
x2 = init.normal_(torch.FloatTensor(3, 4), std = 0.2)
x2

tensor([[ 0.0787, -0.1024, -0.3029,  0.3624],
        [ 0.2480, -0.2081,  0.1725,  0.1084],
        [-0.2173,  0.0300,  0.0827,  0.1917]])

In [36]:
x3 = init.constant_(torch.FloatTensor(3, 4), 3.14159)
x3

tensor([[3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416]])

# Math Operation

In [37]:
a = torch.tensor([1, 2, 3, 4, 5, 6]).view(3, 2)
b = torch.tensor([9, 8, 7, 6, 5, 4]).view(2, 3)
ab = torch.matmul(a, b)
ab
# 행렬곱

tensor([[21, 18, 15],
        [51, 44, 37],
        [81, 70, 59]])

In [38]:
ab = a@b
ab

tensor([[21, 18, 15],
        [51, 44, 37],
        [81, 70, 59]])

In [39]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
add = x1 + x2
add

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [40]:
x1 + 10
# pytorch는 broadcasting을 활용

tensor([[11., 12., 13.],
        [14., 15., 16.]])

In [41]:
x1*x2
# 곱하기

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [42]:
x1*2

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [43]:
x1/x2
# 나누기

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [44]:
x1/5

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])

In [45]:
x1**2
# 거듭제곱

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [46]:
torch.exp(x1)
# exponential

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [47]:
torch.log(x1)
# natural logarithm

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])

In [48]:
x1 = torch.FloatTensor(3, 4)
x2 = torch.FloatTensor(4, 5)
torch.mm(x1, x2).size()

torch.Size([3, 5])

In [49]:
x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.FloatTensor(10, 4, 5)
torch.bmm(x1, x2).size()

# 파이토치는 batch 단위로 연산을 실행하므로 다음과 같은 연산도 가능

torch.Size([10, 3, 5])

In [50]:
torch.dot(torch.tensor([2, 3]), torch.tensor([3, 4]))

tensor(18)

In [53]:
x1 = torch.FloatTensor(2, 3)
x2 = x1.t()
print(x1.size())
print(x2.size())

torch.Size([2, 3])
torch.Size([3, 2])


In [54]:
x1 = torch.FloatTensor(10, 3, 4, 5)
x1.size()

torch.Size([10, 3, 4, 5])

In [55]:
torch.transpose(x1, 1, 2).size()
# 다음과 같이 특정차원끼리만 transpose 가능

torch.Size([10, 4, 3, 5])

In [56]:
torch.transpose(x1, 2, 3).size()

torch.Size([10, 3, 5, 4])

In [63]:
x1 = init.normal_(torch.FloatTensor(4, 4), std = 0.2)
x1

tensor([[-0.0733, -0.0514,  0.3663,  0.1173],
        [-0.1487,  0.1014,  0.1344,  0.0699],
        [ 0.0713, -0.1906, -0.0476,  0.2269],
        [ 0.1978, -0.0180,  0.1148,  0.1669]])

In [64]:
torch.eig(x1, eigenvectors = True)

torch.return_types.eig(eigenvalues=tensor([[-0.1834,  0.1863],
        [-0.1834, -0.1863],
        [ 0.3756,  0.0000],
        [ 0.1385,  0.0000]]), eigenvectors=tensor([[-0.7089,  0.0000, -0.5269,  0.0248],
        [-0.3953, -0.1058, -0.1095,  0.7939],
        [ 0.0891, -0.4581, -0.4286, -0.0677],
        [ 0.2135,  0.2583, -0.7258,  0.6037]]))