# 벡터와 텐서의 element-wise multiplication

In [1]:
import torch
import numpy as np

In [2]:
A = torch.ones(5, 3, 3)
A

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [3]:
v = torch.arange(0, 5)
v

tensor([0, 1, 2, 3, 4])

In [4]:
v_tensor = v.view(v.size()[0], 1, 1)
v_tensor
print(v_tensor.size())

torch.Size([5, 1, 1])


In [5]:
result = v_tensor * A
print(result)
print('result.shape:', result.shape)

# 즉 1 텐서에 순서대로 2차원 텐서에 0부터 4까지 곱해짐

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]])
result.shape: torch.Size([5, 3, 3])


# gather 기능 사용하기

In [6]:
A = torch.arange(1, 10)
A
# 1차원 텐서

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
indices = torch.tensor([0, 3, 5, 6])
print(torch.gather(A, 0, indices))
# 출력은 1차원 텐서
# 즉 배열에서 텐서에 해당되는 인덱스에 있는 값들만을 추출하는 것을 알 수 있다.

tensor([1, 4, 6, 7])


In [8]:
A = torch.arange(25).reshape(5, 5)
A
# 2차원텐서

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [9]:
indices = torch.tensor([
                        [0, 1, 2],
                        [1, 2, 3],
                        [2, 3, 3],
                        [3, 4, 1],
                        [0, 0, 0]
])

print(torch.gather(A, 1, indices))
# 출력도 2차원 텐서

tensor([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 13],
        [18, 19, 16],
        [20, 20, 20]])


In [10]:
A = torch.arange(27).reshape(3, 3, 3)
A
# 3차원 텐서

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [11]:
indices = torch.tensor([
                        [[0, 0, 0], [1, 1, 1], [2, 2, 2]],
                        [[1, 1, 1], [2, 2, 2], [0, 0, 0]],
                        [[0, 1, 2], [0, 1, 2], [0, 1, 2]]])
torch.gather(A, 2, indices)
# 출력도 3차원 텐서

tensor([[[ 0,  0,  0],
         [ 4,  4,  4],
         [ 8,  8,  8]],

        [[10, 10, 10],
         [14, 14, 14],
         [15, 15, 15]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

즉 torch.gather(A, 2, indices)는 지정된 축을 의미한다. 첫번째는 0을 했으므로 해당되는 값을 뽑아내고, 두번째는 1이므로 해당되는 1차원 텐서에서 포함되는 인덱스만을 구성해서 2차원 텐서를 반환하고, 세번째는 2이므로 2차원 텐서에서 해당되는 인덱스 값들만을 뽑아내서 3차원 텐서를 반환하였다.

# expand와 repeat 활용

In [12]:
x = torch.tensor([[1], [2], [3]])
x.size()

torch.Size([3, 1])

In [13]:
x.expand(3, 4)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [14]:
x.expand(-1, 4)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

expand는 크기가 1인 차수를 반복하는 연산이다.

In [15]:
y = torch.rand(3, 1, 1)
y

tensor([[[0.4619]],

        [[0.7409]],

        [[0.9114]]])

In [16]:
y.expand(-1, 3, 4)

tensor([[[0.4619, 0.4619, 0.4619, 0.4619],
         [0.4619, 0.4619, 0.4619, 0.4619],
         [0.4619, 0.4619, 0.4619, 0.4619]],

        [[0.7409, 0.7409, 0.7409, 0.7409],
         [0.7409, 0.7409, 0.7409, 0.7409],
         [0.7409, 0.7409, 0.7409, 0.7409]],

        [[0.9114, 0.9114, 0.9114, 0.9114],
         [0.9114, 0.9114, 0.9114, 0.9114],
         [0.9114, 0.9114, 0.9114, 0.9114]]])

즉 expand는 차원이 1인 값을 반복한다.

In [17]:
x = torch.rand(2, 3)
x

tensor([[0.3954, 0.2789, 0.9888],
        [0.1464, 0.8633, 0.1800]])

In [18]:
x.repeat(3, 2, 2)

tensor([[[0.3954, 0.2789, 0.9888, 0.3954, 0.2789, 0.9888],
         [0.1464, 0.8633, 0.1800, 0.1464, 0.8633, 0.1800],
         [0.3954, 0.2789, 0.9888, 0.3954, 0.2789, 0.9888],
         [0.1464, 0.8633, 0.1800, 0.1464, 0.8633, 0.1800]],

        [[0.3954, 0.2789, 0.9888, 0.3954, 0.2789, 0.9888],
         [0.1464, 0.8633, 0.1800, 0.1464, 0.8633, 0.1800],
         [0.3954, 0.2789, 0.9888, 0.3954, 0.2789, 0.9888],
         [0.1464, 0.8633, 0.1800, 0.1464, 0.8633, 0.1800]],

        [[0.3954, 0.2789, 0.9888, 0.3954, 0.2789, 0.9888],
         [0.1464, 0.8633, 0.1800, 0.1464, 0.8633, 0.1800],
         [0.3954, 0.2789, 0.9888, 0.3954, 0.2789, 0.9888],
         [0.1464, 0.8633, 0.1800, 0.1464, 0.8633, 0.1800]]])

In [19]:
x.repeat(3, 2, 2).shape

torch.Size([3, 4, 6])

(3, 2, 2)텐서에 원래 x의 차원인 (2, 3)이 곱해저 (3, 4, 6)의 텐서가 만들어짐

In [20]:
y = torch.rand(2, 3, 2)
y.repeat(3, 4, 5, 6).shape

torch.Size([3, 8, 15, 12])

expand는 원본 텐서를 참조하여 만들어서 원본 텐서가 변하면 expand한 값도 변한다.

그러나 repeat는 깊은 복사로 만들어저 원본이 변경되더라도 값이 변경이 안된다.

In [21]:
a = torch.rand(1, 1, 3)
a

tensor([[[0.0026, 0.9029, 0.2333]]])

In [22]:
b = a.expand(4, -1, -1)
c = a.repeat(4, 1, 1)

In [23]:
print(b.shape)
print(c.shape)

torch.Size([4, 1, 3])
torch.Size([4, 1, 3])


In [24]:
a[0, 0, 0] = 0
print(a)

tensor([[[0.0000, 0.9029, 0.2333]]])


In [25]:
print(b)

tensor([[[0.0000, 0.9029, 0.2333]],

        [[0.0000, 0.9029, 0.2333]],

        [[0.0000, 0.9029, 0.2333]],

        [[0.0000, 0.9029, 0.2333]]])


값이 변함

In [26]:
print(c)

tensor([[[0.0026, 0.9029, 0.2333]],

        [[0.0026, 0.9029, 0.2333]],

        [[0.0026, 0.9029, 0.2333]],

        [[0.0026, 0.9029, 0.2333]]])


값이 안변함

# topk 기능 사용하기

In [27]:
x = torch.arange(1., 6.)
values, indices = torch.topk(x, 3)
print(values)
print(indices)

tensor([5., 4., 3.])
tensor([4, 3, 2])


즉 텐서에서 제일 큰 값 k개를 추출한다.

In [28]:
x = torch.rand(2, 4, 3)
x

tensor([[[0.2946, 0.2747, 0.9977],
         [0.2986, 0.2504, 0.8388],
         [0.8716, 0.6923, 0.8474],
         [0.1414, 0.3562, 0.4125]],

        [[0.0660, 0.0741, 0.4795],
         [0.1395, 0.2059, 0.0491],
         [0.5789, 0.4427, 0.0404],
         [0.9492, 0.2317, 0.0057]]])

In [29]:
values, indices = torch.topk(x, 2)
print(values)

tensor([[[0.9977, 0.2946],
         [0.8388, 0.2986],
         [0.8716, 0.8474],
         [0.4125, 0.3562]],

        [[0.4795, 0.0741],
         [0.2059, 0.1395],
         [0.5789, 0.4427],
         [0.9492, 0.2317]]])


In [30]:
print(indices)

tensor([[[2, 0],
         [2, 0],
         [0, 2],
         [2, 1]],

        [[2, 1],
         [1, 0],
         [0, 1],
         [0, 1]]])


indices를 이용하면 인덱스를 얻을 수 있고 이를 gather랑 콜라보해서 사용 가능

In [31]:
torch.gather(x, -1, indices) == values

tensor([[[True, True],
         [True, True],
         [True, True],
         [True, True]],

        [[True, True],
         [True, True],
         [True, True],
         [True, True]]])

In [32]:
values, indices = torch.topk(x, 2, dim=1)
print(values)

tensor([[[0.8716, 0.6923, 0.9977],
         [0.2986, 0.3562, 0.8474]],

        [[0.9492, 0.4427, 0.4795],
         [0.5789, 0.2317, 0.0491]]])


In [33]:
print(indices)

tensor([[[2, 2, 0],
         [1, 3, 2]],

        [[3, 2, 0],
         [2, 3, 1]]])


In [34]:
torch.gather(x, 1, indices) == values

tensor([[[True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True]]])

즉 topk로 부터 인덱스를 얻어내면 토치의 gather로 최대값만 뽑아낼 수 있다.

In [35]:
x = torch.rand(3, 4, 5)
y = torch.rand(3, 4, 5)

values, indices = torch.topk(x, 1, dim=2)
# 이 경우 3차원 텐서의 x에서 구성요소인 2차원 텐서내에서 제일 최대값의 값과 위치를 얻어낸다.

In [36]:
torch.gather(y, 2, indices)

tensor([[[0.7895],
         [0.6534],
         [0.7966],
         [0.1729]],

        [[0.6860],
         [0.9038],
         [0.2777],
         [0.3751]],

        [[0.7582],
         [0.9839],
         [0.8514],
         [0.3856]]])

즉 이 값들의 의미는 x의 2차원 축에서 최대값이 위치하는 텐서의 인덱스를 y텐서에서 추출한 것이다.